server:
    port: 8085
spring:
    data:
      mongodb:
        database: clientes
        host: localhost
        port: 27017
    servlet:
        session.timeout: 300s
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
            
face:
  trialMode: true
  serverAddress: /local
  serverPort: 5000
persistence-service:
  enroll: 